dialogues = {
    'Archie': {
        0: {
            1: ["Archie", "Olá, {CTE_PLAYER_NAME}. Você foi muito mal no último teste."],
            2: ["Archie",
                "Você precisa melhorar seu desempenho, se não vai reprovar em Modelagem e Identificação de Sistemas."],
            3: ["Archie", "Eu sei que você tem dificuldades nessa disciplina, então vou te dar uma ajuda."],
            4: ["Archie", "Vá à biblioteca e procure um livro chamado AlexandriA."],
            5: ["Archie", "..."],
            6: ["Archie", "Como esse livro vai te ajudar?"],
            7: ["Archie", "Hahaha! Se eu te contar agora, vai estragar toda surpresa."],
            8: ["Archie", "Apenas siga as instruções contidas no livro, é bem simples."]

        },
    },
    'Euclide': {
        # FASE 1
        1: {
            1: ["???", "Bem-vindo a Alexandria meu jovem aprendiz. Qual o seu nome?"],
            2: ["???", "..."],
            3: ["Euclide", "Muito prazer, {CTE_PLAYER_NAME}. Eu sou Euclide."],
            4: ["Euclide",
                "Vejo aqui nas minhas anotações que você veio de outros tempos, para tentar aprender mais sobre modelos matemáticos, é isso?"],
            5: ["Euclide", "Muito bem! Venha, vamos entrar na biblioteca."],
        },

        # FASE 2
        2: {
            1: ["Euclide",
                "Bem vindo a nossa humilde biblioteca! Temos aqui manuscritos e exemplares de obras e trabalhos que transcendem até mesmo nosso tempo!"],
            2: ["Euclide", "Mas você está aqui por causa de modelagem matemática, então não vamos perder tempo."],
            3: ["Euclide", "Mas antes... Devo te explicar as regras que nós seguimos por aqui."],
            4: ["Euclide",
                "A biblioteca te oferece ajuda e em troca cobramos sua total seriedade com o aprendizado e os desafios propostos."],
            5: ["Euclide", "Te daremos 5 chances para errar, o que pensamos ser mais do que suficiente."],
            6: ["Euclide",
                "Mas caso você falhe na sua jornada... Você terá consequências com seu mestre do lado de fora, se é que me entende."],
            7: ["Euclide", "Chega de enrolação! Vamos direto ao ponto!"],
        },
        3: {
            1: ["Euclide",
                "Este livro na minha mão vai nos guiar na nossa aventura! Preste atenção enquanto eu faço a leitura!"],
            2: ["Euclide", "..."],
            3: ["Euclide", "O quê? Se não é mais fácil eu apenas te dar o livro?"],
            4: ["Euclide", "Hahaha, claro que não meu jovem."],
            5: ["Euclide",
                "Como lhe expliquei, a biblioteca contém conhecimentos que transcendem até mesmo o meu e o seu tempo."],
            6: ["Euclide", "Apenas nós, membros certificados da biblioteca, podemos ler e compreender os livros."],
            7: ["Euclide",
                "Caso você pudesse ler algo que ainda não foi descoberto no seu tempo... Bem, digamos que não seria nada legal..."],
            8: ["Euclide", "..."],
            9: ["Euclide", "Mas vamos logo, você tem um tempo limite aqui comigo!"],
        },

        # FASE 3
        4: {
            1: ["Euclide", "Bem, vamos lá!"],
            2: ["Euclide", "O que são modelos?"],
            3: ["Euclide", "Muito basicamente, modelos são uma forma de representar alguma coisa."],
            4: ["Euclide", "Você consegue me dar um exemplo de um modelo?"]
        },
        5: {
            1: ["Euclide", "Exatamente! Na verdade, todas as quatro opções são exemplos de modelos."],
            2: ["Euclide", "A maquete é capaz de mostrar, em escala, as características construtivas da aeronave."],
            3: ["Euclide",
                "A equação do projétil permite acompanhar a trajetória deste, quando feito o lançamento em uma altura, velocidade e ângulo específicos."],
            4: ["Euclide",
                "O simulador de circuitos é capaz de mostrar o comportamento elétrico deste, através de parâmetros configurados, como resistência ou tensão na fonte."],
            5: ["Euclide",
                "Já a inteligência artificial é um modelo treinado para atuar em certo cenário, como identificar placas de carros, rostos ou classificar espécies de plantas."],
            6: ["Euclide", "Mas aqui vamos focar nos modelos matemáticos."],
            7: ["Euclide",
                "Os modelos matemáticos são representações de um sistema através de hipóteses sobre sua estrutura e seu comportamento."],
            8: ["Euclide",
                "Além de que, diferentes modelos podem representar um mesmo sistema. Mesmo os métodos de obtenção destes sendo iguais."],
            9: ["Euclide", "Vamos fazer um exemplo."],
            10: ["Euclide",
                 "No minigame a seguir, quero que tente posicionar o alcance final do projétil laranja na marca de 'X', controlando a altura e ângulo de lançamento pelos respectivos botões."],
        },
        6: {
            1: ["Euclide",
                "Como você deve ter percebido, com diferentes ajustes você poderia ter obtido o mesmo resultado."],
            2: ["Euclide",
                "Essa é uma peculiaridade dos modelos. Além de diferentes parâmetros, podemos ter diferentes considerações."],
            3: ["Euclide", "Por exemplo, no minigame a velocidade de saída ajustável poderia ser considerada."],
            4: ["Euclide",
                "Tenho outros exemplos considerando outras áreas da ciência."],
            5: ["Euclide",
                "Se modelarmos um resistor, sua resistência poderia ser função também da temperatura ou deformação."],
            6: ["Euclide",
                "Ou se modelarmos o movimento de um corpo, a força de atrito poderia ser função também da velocidade ou da rugosidade da superfície."],
            7: ["Euclide",
                "Mas agora que tratamos de alguns tipos de modelos e como podem ser formados, você pode me perguntar..."],
            8: ["Euclide", "'Mas por que eu deveria usar um modelo?'"],
            9: ["Euclide", "Vamos usar uma simulação pra tentarmos formular uma resposta."],
            10: ["Euclide", "Suponha que você precisa controlar a temperatura de fluido no tanque."],
            11: ["Euclide",
                 "Você sabe apenas que o fluido é extremamente volátil e que se seu volume extrapolar o do tanque e for exposto ao ar, acontece uma explosão."],

        },
        7: {
            1: ["Euclide",
                "Você não sabia, mas acima de 60ºC, o fluído se expandia 2% por segundo. Acima de 80ºC, 5% por segundo."],
            2: ["Euclide",
                "Além disso, se a temperatura passasse de 80ºC, diminuir a temperatura não pararia a expansão."],
            3: ["Euclide",
                "Se você possuísse um modelo desse sistema, talvez você não tivesse deixado a explosão acontecer."],
            4: ["Euclide", "Isso pode ser expandido para mais exemplos."],
            5: ["Euclide",
                "Como o modelo mental que você cria ao fazer um curso de culinária, permitindo você executar certas técnicas adequadamente."],
            6: ["Euclide", "Ou os modelos atmosféricos, que permitem que saibamos a temperatura de toda a semana."],
            7: ["Euclide",
                "O que quero dizer é, com esses modelos em mão, podemos agir com maior segurança no sistema, evitando acidentes."],
            8: ["Euclide",
                "Podemos também antecipar fenômenos não desejados, ou valores futuros que uma saída do sistema possa atingir."],
            9: ["Euclide",
                "Além de permitir implementar técnicas de controle em tempo real, otimizando o desempenho do sistema."],
            10: ["Euclide",
                 "Finalizada essa contextualização inicial, vamos fazer um pequeno teste. Você precisa acertar pelo menos 3 perguntas, então se concentre."],
        },
        8: {
            1: ["Euclide", "Muito bem! Agora, vamos para a parte divertida!!!"],
            2: ["Euclide", "Como podemos obter esses modelos?"],
            3: ["Euclide", "..."],
            4: ["Euclide", "Vou te ensinar sobre as técnicas de identificação de sistemas."],
        },

        # FASE 4
        9: {
            1: ["Euclide",
                "Como comentei anteriormente, os modelos possuem uma ampla variedade de utilidades para várias aplicações."],
            2: ["Euclide",
                "Então obter modelos capazes de representar nosso sistema também é muito importante."],
            3: ["Euclide",
                "Mas como conseguimos obter esses modelos?"],
            4: ["Euclide",
                "Inicialmente, poderíamos tentar equacionar todo o nosso sistema utilizando equações da física."],
            5: ["Euclide",
                "Isso é viável para sistemas simples, como o movimento de um pêndulo, por exemplo."],
            6: ["Euclide",
                "No entanto, quando lidamos com sistemas mais complexos, como um avião em voo ou uma planta industrial com múltiplas entradas e saídas é inviável."],
            7: ["Euclide",
                "Equacionar tudo com base apenas na física se torna extremamente difícil, podendo gerar um gasto enorme de tempo e de dinheiro."],
            8: ["Euclide", "Nesses casos, uma alternativa poderosa é recorrer à Identificação de Sistemas."],
            9: ["Euclide",
                "Essa abordagem permite obter modelos matemáticos a partir de dados experimentais, sem precisar conhecer todas as leis físicas envolvidas."],
            10: ["Euclide", "Para realizar a identificação de sistemas, podemos seguir 5 passos principais:"],
            11: ["Euclide", "1 - Coleta de dados."],
            12: ["Euclide", "2 - Escolha da representação matemática."],
            13: ["Euclide", "3 - Determinação da estrutura do modelo."],
            14: ["Euclide", "4 - Obtenção dos parâmetros do modelo."],
            15: ["Euclide", "5 - Validação do modelo."],
            16: ["Euclide", "Vamos começar com a coleta de dados."],
            17: ["Euclide",
                 "Esta é uma das partes mais críticas da identificação de sistemas, já que nossos modelos são construídos a partir dos dados."],
            18: ["Euclide",
                 "Se os dados forem ruins, incompletos ou ruidosos demais, o modelo resultante também será ruim."],
            19: ["Euclide",
                 "Vamos fazer um exemplo. A seguir, você terá as leituras de um sensor de temperatura de uma planta industrial."],
            20: ["Euclide",
                 "Apenas sabendo que a temperatura da planta se manteve constante, tente saber o valor desta pelos dados coletados através do sensor."],

        },
        10: {
            1: ["Euclide",
                "Acertando ou errando o valor, você concorda que não foi possível avaliar facilmente o padrão dos dados e seu valor?"],
            2: ["Euclide", "Esses dados que você observou, tinham uma parcela enorme de ruído acrescidos ao sinal."],
            3: ["Euclide",
                "Algumas causas de ruído em medições são: interferências eletromagnéticas próximas ao sensor, circuitos ou componentes de baixa qualidade ou interferência humana."],
            4: ["Euclide",
                "Uma saída para resolver problemas de ruído são os filtros. Como o nome sugere, vamos pegar uma parte indesejada e tirar dos nossos dados."],
            5: ["Euclide",
                "Os filtros podem assumir diversas formas, como um circuito elétrico..."],
            6: ["Euclide", "... um algoritmo computacional..."],
            7: ["Euclide", "... ou até mesmo uma espuma acústica em um microfone e um auditório de um teatro."],
            8: ["Euclide",
                "Mas assim como os filtros podem nos auxiliar, eles podem ser prejudiciais para o nosso processo."],
            9: ["Euclide",
                "Um filtro de barro, se sua vela estiver suja, o processo de filtragem pode ser prejudicado."],
            10: ["Euclide",
                 "Da mesma forma, filtros de baixa ordem ou mal dimensionados podem mudar a forma do seu sinal útil e não rejeitar adequadamente a parte indesejada."],
            11: ["Euclide",
                 "Podem também causar atrasos em componentes específicas do sinal ou até retirar informações desejadas do resultado final."],
            12: ["Euclide",
                 "Por isso, é importante conhecer bem o fenômeno estudado antes de utilizar um filtro, qualquer que seja o tipo."],
            13: ["Euclide",
                 "Continuando a nossa conversa sobre frequências, vamos falar sobre a frequência de amostragem do sinal."],
            14: ["Euclide",
                 "A frequência ou taxa de amostragem é basicamente quantas vezes iremos monitorar ou fazer aquisição do sinal dentro de um segundo."],
            15: ["Euclide", "Para contextualizar melhor, vamos para um minigame."],
            16: ["Euclide",
                 "Selecione a taxa de amostragem de modo que o sinal adquirido (pontos vermelhos) consigam representar o sinal referência (senoide cinza)."],
        },
        11: {
            1: ["Euclide",
                "Como deve ter percebido, acima de certa taxa de amostragem, os dados adquiridos representam bem o fenômeno."],
            2: ["Euclide",
                "Mas você pode se perguntar: 'Então não deveria apenas aumentar ao máximo o valor da frequência de aquisição?'"],
            3: ["Euclide",
                "Nem sempre! Quanto maior sua taxa de amostragem, mais rápido devem ser as leituras do seu sensor."],
            4: ["Euclide",
                "Isso pode elevar os custo do sensor e do sistema de aquisição de dados, para que sejam capazes de trabalhar nessa alta frequência."],
            5: ["Euclide",
                "Além do maior volume de armazenamento dos dados no sistema."],
            6: ["Euclide",
                "Então é tudo uma questão de balanço, você não precisa de uma motosserra pra descascar uma laranja! Hahaha! Mas também não precisa usar apenas as mãos."],
            7: ["Euclide", "Um último ponto a ser tratado aqui, são os sinais de excitação do sistema."],

            8: ["Euclide", "Vamos inicialmente supor que o sistema que desejamos modelar é sua rotina semanal."],
            9: ["Euclide", "A obtenção de dados ocorre por meio de perguntas que vou lhe fazer."],
            10: ["Euclide",
                 "Você concorda que não sou capaz de modelar sua semana se eu apenas perguntar 'Ei {CTE_PLAYER_NAME}, o que você fez ontem a noite?'"],
            11: ["Euclide",
                 "Ou se eu perguntar '{CTE_PLAYER_NAME}, me conte sobre seu almoço de dois dias atrás.'"],
            12: ["Euclide", "Não faz muito sentido, certo?"],
            13: ["Euclide",
                 "Quando estamos identificando um sistema, queremos que o modelo consiga representar bem todos os seus comportamentos."],
            14: ["Euclide",
                 "Então é importante fazer as perguntas certas para nosso objeto de estudo, sendo bem abrangente nas informações obtidas."],
            15: ["Euclide",
                 "Uma pergunta melhor seria '{CTE_PLAYER_NAME}, consegue me descrever como foram seus últimos dias? O que fez, onde foi, o que comeu?'"],
            16: ["Euclide",
                 "Tendo esse primeiro contexto, me responda, quais componentes de frequência você acha que deve ter um bom sinal de excitação para modelar o sistema?"],
        },
        12: {
            1: ["Euclide",
                "Um bom sinal de excitação deve abranger, idealmente, todo o espectro de frequência (ou pelo menos a maior parte dele)."],
            2: ["Euclide",
                "Dessa forma, estamos explorando os diversos comportamentos e respostas que o sistema pode dar."],
            3: ["Euclide", "Um sinal com essas características, que é bem famoso, é o ruído branco."],
            4: ["Euclide",
                "Onde temos um sinal aleatório, com amplo espectro de frequências e a mesma amplitude para todas as componentes."],
            5: ["Euclide", "Esse nome vem do Disco de Newton, que contém as cores de todo o espectro visível."],
            6: ["Euclide",
                "Quando giramos o disco, acontece a mistura de todo esse espectro, ficando apenas a cor branca visível"],

            7: ["Euclide", "Mas aqui, vamos tratar de um sinal específico: O sinal binário pseudoaleatório, ou PRBS."],
            8: ["Euclide",
                "O PRBS é um sinal que assume dois valores, isto é, ou 0 ou 1. Ou liga ou desliga a fonte de sinal."],
            9: ["Euclide",
                "Ele também se assemelha a um ruído, tendo um amplo espectro de frequências e autocorrelação similar a um impulso."],
            10: ["Euclide",
                 "Além disso, é um sinal periódico e determinístico. Isto é, a partir de um estado inicial (chamada seed), sempre se chega a mesma sequência do sinal PRBS."],
            11: ["Euclide", "Por isso 'pseudoaleatório'."],
            12: ["Euclide",
                 "E o sinal se repete em intervalos predefinidos, já que seu parâmetro número de bits define a quantidade de estados máximo do sinal, conferindo periodicidade."],
            13: ["Euclide", "Um último parâmetro deste tipo de sinal que deve ser considerado é o tempo entre bits."],
            14: ["Euclide",
                 "Resumidamente é o tempo em que o sinal vai manter num determinado valor da sequência PRBS (ou bit), antes de ir para o próximo valor."],
            15: ["Euclide",
                 "É muito importante dimensionar bem este valor, de forma que o sinal consiga excitar adequadamente o sistema."],
            16: ["Euclide",
                 "O tempo entre bits não pode ser muito pequeno de modo a não pegar as dinâmicas do transitório do sistema."],
            17: ["Euclide",
                 "Mas, ele também não pode ser muito grande, fazendo com que o regime permanente se estenda."],
            18: ["Euclide",
                 "Devemos conseguir captar a dinâmica completa do sistema, fazendo uma escolha adequada desse tempo."],
            19: ["Euclide",
                 "Vamos tentar aplicar esse conceito do tempo entre bits para excitar as dinâmicas do sistema."],
            20: ["Euclide",
                 "Na simulação a seguir, temos a resposta do circuito RC acima à uma entrada PRBS."],
            21: ["Euclide",
                 "Esse sinal PRBS tem 7 bits, o que faz ele se repetir a cada 127 estados, e tem uma seed qualquer, definida aqui como 10001."],
            22: ["Euclide",
                 "Experimente variar o tempo entre bits do sinal PRBS e observar como a resposta do sistema muda."],

        },
        13: {
            1: ["Euclide",
                "Percebeu que para valores menores, a resposta era meio picotada? Isto é, que o sinal não conseguiu excitar as dinâmicas?"],
            2: ["Euclide",
                "Além de que para valores maiores, o PRBS se parece muito com um conjunto de degraus? Sinal que não é o mais adequado para tarefas de identificação."],
            3: ["Euclide",
                "Existem algumas heurísticas, ou regras de bolso, para determinar o melhor tempo entre bits para um sistema."],
            4: ["Euclide",
                "O professor Luis Aguirre apresenta a regra acima, onde escolhemos o valor do tempo entre bits Tb a partir da menor constante de tempo do sistema (dada por tau mínimo)."],
            5: ["Euclide",
                "Mantendo o valor do tempo entre bits dentre desse intervalo, é bem provável que excitaremos bem o nosso sistema para a obtenção dos dados."],
            6: ["Euclide",
                "O valor da constante de tempo pode ser obtido pela resposta ao degrau do sistema."],
            7: ["Euclide",
                "Isso mostra a importância de conhecer bem o nosso sistema e, os meios de obter as respostas que precisamos dele."],
            8: ["Euclide", "Para finalizar essa seção, vamos novamente para um quiz rápido."],
        },
        14: {
            1: ["Euclide",
                "Agora que entendemos melhor sobre a parte de obtenção dos dados de entrada e saída, vamos para a próxima etapa..."],
            2: ["Euclide", "A escolha da representação matemática."]
        },

        # FASE 5
        15: {
            1: ["Euclide",
                "Escolher uma representação de um sistema é uma tarefa que depende do tipo de sistema e do objetivo da modelagem."],
            2: ["Euclide",
                "Vamos supor que queremos escolher a representação a ser usada no modelo de uma bicicleta."],
            3: ["Euclide",
                "Se formos tratar com uma criança de 7 anos, a representação pode ser um conjunto de rabiscos simples."],
            4: ["Euclide",
                "Se formos tratar com um piloto de Mountain Bike, a representação pode ser a descrição de cada peça e seu fabricante."],
            5: ["Euclide",
                "Se formos tratar com um engenheiro mecânico, a representação pode ser um conjunto de equações diferenciais ou o desenho CAD da bicicleta."],
            6: ["Euclide",
                "As representações matemáticas devem ser definidas de acordo com o grau de detalhe ou complexidade a serem conferidas na modelagem."],
            7: ["Euclide",
                "Mas além disso, a representação deve ser escolhida de forma a representar os comportamentos dinâmicos e estáticos do sistema."],
            8: ["Euclide",
                "Me responda uma pergunta:"],
        },

        16: {
            1: ["Euclide",
                "É importante saber reconhecer o tipo de fenômeno que estamos lidando."],
            2: ["Euclide",
                "Não vamos ter bons resultados modelando a senoide mostrada usando uma reta."],
            3: ["Euclide",
                "Não conseguiremos que nosso modelo represente um sistema extremamente não linear, se nossa formulação for simplesmente linear."],
            4: ["Euclide",
                "Além de funções como reta, senoide, exponencial, logarítmica e polinomial, existem outras representações matemáticas."],
            5: ["Euclide",
                "Uma que está muito em alta na sua época é a Inteligência Artificial."],
            6: ["Euclide",
                "Esta, utiliza diversas representações matemáticas, como redes neurais, para modelar sistemas complexos."],
            7: ["Euclide",
                "Essas redes neurais são compostas de diversas camadas de neurônios, que se comunicam entre si e aprendem a partir de dados a forma de resolver problemas."],
            8: ["Euclide",
                "Eu gostaria de focar em um tipo de representação matemática específica, que são os modelos NARMAX Polinomiais."],
            9: ["Euclide",
                "NARMAX é um acrônimo para Nonlinear AutoRegressive Model with Moving Average and eXogenous inputs."],
            10: ["Euclide",
                 "Em português, seria algo como 'Modelo Não Linear Auto-Regressivo de Média Móvel com Entradas Exógenas'."],
            11: ["Euclide",
                 "Esses modelos são capazes de representar sistemas não lineares, com entradas e saídas, além de ruídos."],
            12: ["Euclide",
                 "Na imagem acima, temos o formato geral de um modelo NARMAX Polinomial."],
            13: ["Euclide",
                 "Regressores aqui podemos tratar como variáveis. Os valores destes regressores normalmente são as entradas e saídas monitoradas do sistema, por meio de sensores."],
            14: ["Euclide",
                 "Já os atrasos são deslocamentos temporais de cada regressor."],
            15: ["Euclide",
                 "Por exemplo, do modelo acima podemos dizer que a saída no instante k, é dada pelo valor constante 0.5, multiplicado pelo regressor da saída com atraso 3."],
            16: ["Euclide",
                 "Isto é, o valor a ser utilizado para cálculo é o valor à três instantes de tempo atrás."],
            17: ["Euclide",
                 "Vamos supor que temos os valores acima para o regressor da saída. No instante k (em verde), o valor será 1.5."],
            18: ["Euclide",
                 "Pois 0.5 vezes 3, que é o valor do regressor com atraso 3 (em amarelo), é igual a 1.5."],
            19: ["Euclide",
                 "Vamos fazer um exercício rápido para fixar esse conceito. Pegue lápis, papel e uma calculadora e me responda:"],
            20: ["Euclide",
                 "A partir dos valores dos regressores de entrada e saída mostrados, e do modelo apresentado, qual o valor da saída no instante k?"],

        },
        17: {
            1: ["Euclide",
                "Vamos continuar analisando o modelo NARMAX. A letra “F” representa uma função de base polinomial, isto é, uma soma de termos lineares e não lineares."],
            2: ["Euclide",
                "A letra “l” minúscula representa o grau máximo de não linearidade presente no nosso polinômio."],
            3: ["Euclide",
                "Isso implica que o número de regressores que formam um componente ou agrupamento do polinômio, não pode ser maior que esse grau."],
            4: ["Euclide",
                "Por exemplo, no modelo acima, o grau máximo de não linearidade é 3, pois no primeiro agrupamento do polinômio, temos 3 regressores se multiplicando."],
            5: ["Euclide",
                "E como no segundo agrupamento do polinômio temos apenas 2 regressores, o grau máximo de não linearidade é 3."],
            6: ["Euclide",
                "Já aquela letra esquisita, chamada Xi, representa os resíduos do processo de identificação. Ou seja, o valor real da saída é comparado com o valor predito pelo modelo."],
            7: ["Euclide",
                "O que sobrou entre essa diferença, é justamente o resíduo. Podemos escutar os resíduos serem tratados como erro do modelo."],
            8: ["Euclide",
                "Na figura acima podemos ver, os dados obtidos de um ensaio em laranja. Podemos ajustar uma curva que segue a tendência dos dados, que está em azul."],
            9: ["Euclide",
                "Os traços verdes, que ligam os pontos laranja com a curva azul, representam os resíduos do modelo. Modelo, neste caso, é a equação da curva azul."],
            10: ["Euclide",
                 "Guarde bem esse conceito, pois ele será muito importante mais adiante."],
            11: ["Euclide",
                 "Mas sabendo o básico do modelo NARMAX Polinomial, você ainda pode se perguntar: 'Mas por que tratamos sobre este tipo de modelo?'"],
            12: ["Euclide",
                 "Eu particularmente gosto muito dele, porque ele apresenta parâmetros constantes, tornando a obtenção destes em um processo totalmente linear."],
            13: ["Euclide",
                 "Vamos conversar mais sobre obtenção dos parâmetros um pouco mais a frente."],
            14: ["Euclide",
                 "Vou citar alguns outros tipos de modelos, para você pesquisar: Modelos NARMAX Fourier, Redes Neurais NARX, Representação em espaço de estados, Funções de transferência, e por aí vai."],
            15: ["Euclide",
                 "Tendo agora nossa representação matemática definida, vamos para a próxima etapa... A determinação da estrutura do modelo."],
            16: ["Euclide",
                 "Para contextualizar essa etapa, vou tentar te mostrar um grande problema do nosso processo de identificação."],
            17: ["Euclide",
                 "Suponha que estamos modelando um sistema com 1 entrada e 1 saída. Inicialmente, grau de não linearidade 1 máximo. Vamos supor também que o atraso máximo nos dois regressores é 1."],
            18: ["Euclide",
                 "Temos os possíveis termos acima para compor o nosso modelo NARMAX Polinomial."],
            19: ["Euclide",
                 "São 3 termos possíveis, o que acaba sendo bem simples o processo de determinar qual a combinação desses termos forma nosso modelo."],
            20: ["Euclide",
                 "Vamos agora aumentar o grau de não linearidade máximo para 2, mantendo os mesmos atrasos e número de entradas e saídas."],
            21: ["Euclide",
                 "Vemos acima, que apenas aumentando o grau de não linearidade máximo, já aumenta exponencialmente o número de termos possíveis."],
            22: ["Euclide",
                 "Agora pense quando aumentarmos o valor dos atrasos máximos, ou o número de entradas e saídas do sistema. Esse número de termos possíveis aumenta absurdamente."],
            23: ["Euclide",
                 "Pense agora como seria a tarefa de saber qual combinação desses termos melhor representa o sistema. Não é uma tarefa fácil de ser feita."],
            24: ["Euclide",
                 "Um dos primeiros a solucionar esse problema, foi o professor Hirotogu Akaike."],
            25: ["Euclide",
                 "Akaike usou uma teoria que diz que um modelo que tenta representar um sistema, nunca será perfeito e alguma informação será perdida."],
            26: ["Euclide",
                 "Ele então desenvolveu o Critério de Informação de Akaike, ou AIC."],
            27: ["Euclide",
                 "Esse critério estima quanta informação um modelo perdeu em relação aos dados reais e, baseando no número de componentes do modelo, faz um ranking dos modelos considerados."],
            28: ["Euclide",
                 "Utilizando o AIC, podemos saber quais termos de regressores devem ser utilizados para compor o modelo, sabendo quais farão com que o modelo perca menos informação."],
            29: ["Euclide",
                 "Mas além disso, usando o AIC, conseguimos determinar a quantidade de agrupamentos ou termos representa suficientemente bem o modelo."],
            30: ["Euclide",
                 "Isso é importante, pois podem ter casos em que a adição de mais e mais termos não tem uma contribuição real para o modelo final."],
            31: ["Euclide",
                 "Vamos jogar outro minigame. Teremos uma senoide com dados reais e uma curva representando o ajuste do modelo."],
            32: ["Euclide",
                 "Selecione os termos de regressores, de forma a diminuir o valor do AIC. Faça com muito cuidado, este é pra valer!"],
        },
        18: {
            1: ["Euclide",
                "Agora que entendemos como determinar a estrutura do modelo, vamos para a próxima etapa..."],
            2: ["Euclide",
                "A obtenção dos parâmetros do modelo."],
            3: ["Euclide",
                "Os parâmetros vão definir o quanto cada agrupamento de regressores influencia na saída do modelo."],
            4: ["Euclide",
                "Podemos pensar num exemplo simples, como uma máquina que faz sucos. Você tem três botões: um para água, outro para açúcar e outro para a polpa."],
            5: ["Euclide",
                "Se você adicionar muita água, o suco fica aguado. Se colocar muito açúcar, fica doce demais. E se colocar muita polpa, fica grosso."],
            6: ["Euclide",
                "Você precisa ajustar a quantidade de cada ingrediente para fazer o suco que atende seu gosto."],
            7: ["Euclide",
                "Mesmo com uma estrutura bem selecionada, se os parâmetros não forem ajustados corretamente, o modelo não vai funcionar bem."],
            8: ["Euclide",
                "No nosso modelo de estudo, o NARMAX Polinomial, os parâmetros são os coeficientes que multiplicam cada agrupamento de regressores."],
            9: ["Euclide",
                "Por exemplo, nesse modelo já mostrado aqui anteriormente, o parâmetro do regressor da saída com atraso 3 é 0.5."],
            10: ["Euclide",
                 "Nos modelos NARMAX Polinomiais, os parâmetros são SEMPRE valores constantes, o que torna a obtenção deles um processo linear."],
            11: ["Euclide",
                 "Isso não acontece sempre, podemos ter modelos que os parâmetros variam com o tempo. Como o modelo populacional, que tem taxa de crescimento variável sazonalmente."],
            12: ["Euclide",
                 "Os parâmetros de uma rede neural ou de uma tabela Q em aprendizagem por reforço são atualizados durante o processo de treinamento."],
            13: ["Euclide",
                 "Considere a forma matricial do modelo NARMAX Polinomial, mostrada acima."],
            14: ["Euclide",
                 "A matriz y tem os valores da saída do sistema, obtidas na primeira etapa do processo de identificação."],
            15: ["Euclide",
                 "A matriz Psi é a matriz dos regressores. Nela, temos em cada coluna um agrupamento de regressores, e em cada linha o valor do regressor no instante k."],
            16: ["Euclide",
                 "A matriz Theta contém os parâmetros do modelo, que são os coeficientes que multiplicam cada agrupamento de regressores."],
            17: ["Euclide",
                 "O chapéu na matriz Theta indica que é uma estimativa dos parâmetros, obtida a partir dos dados experimentais."],
            18: ["Euclide",
                 "A matriz Xi, dos resíduos, é a diferença entre a matriz y e o produto da matriz Psi com a matriz Theta. E queremos reduzir ao máximo os resíduos."],
            19: ["Euclide",
                 "A partir dessa equação, podemos obter os parâmetros do modelo utilizando o método dos mínimos quadrados."],
            20: ["Euclide",
                 "O método dos mínimos quadrados é uma técnica matemática que busca minimizar a soma dos quadrados dos resíduos."],
            21: ["Euclide",
                 "São usados quadrados, pois os resíduos podem ser positivos ou negativos, e queremos evitar que se cancelem."],
            22: ["Euclide",
                 "Existem diversas metodologias para estimação de parâmetros usando mínimos quadrados, como os mínimos quadrados médios, mínimos quadrados recursivos, e mínimos quadrados totais."],
            23: ["Euclide",
                 "Com uma rápida pesquisa na internet, você encontra ferramentas que permitem a aplicação desses métodos baseados em mínimos quadrados, de forma rápida e fácil."],
            24: ["Euclide",
                 "Vamos ver um pouco mais de ajuste de parâmetros na simulação a seguir."],
            25: ["Euclide",
                 "Você terá os dados amostrados acima, onde eu ajustarei duas curvas para modelar esses dados, considerando um modelo de segundo grau."],
            26: ["Euclide",
                 "Uma será através do método de mínimos quadrados (LS)..."],
            27: ["Euclide",
                 "E a outra será ajustada utilizando um outro método alternativo, bem menos preciso que o de mínimos quadrados."],
            28: ["Euclide",
                 "Deixarei então a possibilidade de você controlar os três parâmetros do modelo de segundo grau: p0 que é a parte constante, p1 que é o de primeiro grau e p2 que é o de segundo."],
            29: ["Euclide",
                 "Deixarei também, a avaliação do erro quadrático médio (EQM) entre os dados amostrados e cada curva."],
            30: ["Euclide",
                 "Quanto menor o valor do EQM, melhor a curva se ajusta aos dados amostrados."],
            31: ["Euclide",
                 "Dessa forma, tente ajustar a curva manual (em vermelho) aos dados amostrados, tentando minimizar o valor de EQM."],

        },
        19: {
            1: ["Euclide",
                "Percebeu que não foi possível ajustar uma curva que tivesse um EQM menor que a de mínimos quadrados?"],
            2: ["Euclide",
                "Ao minimizar a soma do quadrado dos resíduos com LS, temos a solução ótima do problema de ajuste"],
            3: ["Euclide",
                "Vamos agora para a validação dos modelos."],
            4: ["Euclide",
                "O modelo não necessariamente precisa ser perfeito, mas deve ser capaz de representar bem o sistema e resolver o problema do usuário."],
            5: ["Euclide",
                "Então, a validação do modelo é uma etapa crucial para garantir que o modelo atende às expectativas e requisitos do usuário."],
            6: ["Euclide",
                "Um exemplo de processo de validação, seria você olhar o quadro de um pintor e a paisagem que ele tentou representar, e avaliar se achou parecido ou não."],
            7: ["Euclide",
                "Ou se você conseguisse sentir as emoções que ele queria transmitir com a pintura."],
            8: ["Euclide",
                "O importante a se dizer é que, não existe um processo de validação único e universal para todos os modelos."],
            9: ["Euclide",
                "Podemos validar um modelo matemático observando o gráfico comparando dados reais e dados preditos pelo modelo."],
            10: ["Euclide",
                 "Podemos validar um modelo através de métricas de erro, como o erro médio absoluto, erro quadrático médio, ou erro médio de predição."],
            11: ["Euclide",
                 "Os valores desses erros derivam do processo de estimação de parâmetros, já que naquela etapa o objetivo é justamente minimizar este valor em questão."],
            12: ["Euclide",
                 "Vamos fazer outra simulação. Desta vez, vamos ver o porque é importante termos diversos recursos de validação."],
            13: ["Euclide",
                 "Nós temos agora um conjunto de dados amostrados e uma curva de ajuste. Dessa vez, vamos controlar apenas o grau do ajuste."],
            14: ["Euclide",
                 "Temos também apresentado, o valor do erro quadrático médio entre os dados e a curva ajustada."],
            15: ["Euclide",
                 "Brinque com os controles e, perceba como aumentar o grau do ajuste tem uma melhora na métrica de EQM, mas o ajuste claramente fica inadequado."],

        },
        20: {
            1: ["Euclide",
                "Quando o grau do ajuste é desnecessariamente maior que o necessário, acontece o fenômeno de overfitting, ou sobreajuste."],
            2: ["Euclide",
                "Quando o grau é abaixo do necessário, acontece o underfitting, ou subajuste."],
            3: ["Euclide",
                "Outras duas avaliações de validação são a autocorrelação dos resíduos e a correlação cruzada dos resíduos."],
            4: ["Euclide",
                "A autocorrelação dos resíduos avalia se os resíduos estão correlacionados entre si, ou seja, se há dependência temporal entre eles."],
            5: ["Euclide",
                "O bom modelo, tem esse gráfico parecido com um impulso, ou seja, no atraso 0 ele é idealmente unitário. Nos demais valores, ele cai dentro do intervalo de confiança."],
            6: ["Euclide",
                "Na correlação cruzada dos resíduos, avaliamos se o resíduo e a entrada estão correlacionados entre si."],
            7: ["Euclide",
                "Se o modelo está bem ajustado, todo o gráfico de correlação cai dentro do intervalo de confiança, ou seja, não há correlação entre os resíduos e a entrada."],
            8: ["Euclide",
                "Essa análise é importante, pois se houver correlação entre os resíduos e a entrada, significa que o modelo não está capturando todas as dinâmicas do sistema."],
            9: ["Euclide",
                "Vamos fazer um quiz, para finalizar esses conceitos abordados."],
        },
        21: {
            1: ["Euclide",
                "Parabéns, {CTE_PLAYER_NAME}. Acredito que você conseguiu aprender os principais conceitos sobre modelagem e identificação de sistemas."],
            2: ["Euclide",
                "Mas lembre que, eu apenas te dei um empurrãozinho. Procure aprender cada vez mais sobre os assuntos que tratamos aqui."],
            3: ["Euclide",
                "Você já ficou tempo demais aqui, hora de ir pra sua era. Até logo."],
        }
    },

}
